config/routes.rb
Tradeya::Application.routes.draw do


  resources :trade_communications


  resources :passive_trades do
    member do
      get :my_haves_tab
      get :communication_tab
      get :trader_haves_tab
    end
    resources :transactions
  end

  mount Resque::Server, :at => "/resque"

  # root :to => "home#index"
  root :to => "home#invite"
  # match 'invite' => 'home#invite'
  match 'friends_invite' => 'users#friends_invite'
  match 'home' => 'home#index'
  match 'trade_page' => 'items#trade_page'

  match 'welcome' => 'home#welcome'
  match 'holiday' => 'home#holiday'
  match 'getstarted' => 'home#getstarted'

  resources :accepted_offers, :only => [:create]
  resources :comments,:only => [:create,:destroy]
  resources :authentications
  resources :reviews

  # post 'charges/create'
  #post "charge_cards/create"
  resources :charge_cards, :only => [:index,:create,:destroy]
# mailboxer
  resources :conversations, :only => [:show] do
    member do
      post 'reply'
      get 'download'
      get 'displaytrash'
      get 'displayinbox'
      get 'trash'
      get 'markasunread'
      get 'markasread'
      get 'delete'
      get 'untrash'
      get 'newmsg'
    end
  end
  # match 'conversations/trash' => 'conversations#trash', via: [:post]

  resources :verify_phone_number do
    member { post 'twilio_hack' }
    member { post 'show' }
  end

  resources :trades do
    member do
      post :reject
      #   post :rate
      get :my_haves_tab
      get :communication_tab
      get :trader_haves_tab
      get :confirm
      post :complete
      get :accept_terms
      post :update
    end
    resources :transactions 
  end
  match "transactions/get_shipping" => "transactions#get_shipping"
   match "transactions/update_address" => "transactions#update_address"
   match "transactions/trade_review" => "transactions#trade_review"
   match "transactions/make_trade" => "transactions#make_trade"
  # Namespace for mobile api
  namespace :api, defaults:{format: 'json'} do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'
      end

      # items api calls
      get 'items' => 'items#index', :as => 'items'
      post 'items' => 'items#create'
      get 'items/:id' => 'items#show'
      post 'items/:id/likes' => 'items#likes'
      post 'items/:id/wants' => 'items#wants'
      post 'items/:id/haves' => 'items#haves'
      post 'items/:id/comment' => 'items#comment'

      get 'categories' => 'home#categories'

      # user profile api
      get 'users/:id' => 'users#show'
      get 'users/:id/likes' => 'users#likes'
      get 'users/:id/wants' => 'users#wants'
      get 'users/:id/haves' => 'users#haves'
      get 'users/:id/following' => 'users#followed_users'
      get 'users/:id/followers' => 'users#followers'
      post 'users/:id/follow' => 'users#follow'
      get 'users/:id/past_trades' => 'users#past_trades'
      post 'users/search' => 'users#search'
    end
  end

  ActiveAdmin.routes(self)
  devise_for :users,
  :controllers => {
    :registrations => 'registrations',
    :passwords => 'passwords',
    :sessions => 'sessions',
    :confirmations => 'confirmation'}
    # :invitations => 'invitations'}

  devise_scope :user do
    match 'failure' => 'sessions#failure'
    match 'update_zip' => 'registrations#update_zip', :as => :update_zip
    match 'update_account_settings' => 'registrations#update_account_settings', :as => :update_account_settings
    match 'change_user_password' => 'registrations#change_user_password', :as => :change_user_password
    match 'deactivate_account' => 'registrations#deactivate_account', :as => :deactivate_account
    match 'create_guest' => 'registrations#create_guest', :as => :create_guest, :via => :post
    match 'update_guest' => 'registrations#update_guest', :as => :update_guest, :via => :post
    match 'guest_deactivate_account' => 'registrations#guest_deactivate_account', :as => :guest_deactivate_account
  end

  # resources :items, :only => [:create, :show, :new]
  resources :items do
    member do
      post 'like'
      post 'haves'
      post 'wants'
      get 'trade_offers'
      get 'my_offers'
      get 'accepted_offers'
      get 'rejected_offers'
      get 'wants_detail'
      post 'remove_have'
      post 'remove_offer'
      post 'want_cancel'
      post 'main_photo'
      post 'request_info'
      post 'edit_photo'
    end
  end

  resources :users, :only => [:show, :edit, :update] do
    member do
      post 'follow'
      get 'dashboard'
      get 'wants'
      get 'haves'
      get 'likes'
      get 'reviews'
      get 'following'
      get 'followers'
      get 'facebook_friends'
      get 'twitter_friends'
      get 'following_tab_search'
      get 'past_trades'
      get 'myoffers'
      get 'activity_feed'
      get 'inbox'
      post 'inbox'
      get 'sort_review'
      get 'settings'
      get 'invite'
      get 'pvt_msg_tab'
      get 'messaging'
      # get 'notifications'
      get 'inbox/messaging'
      get 'inbox/notifications'
      # post 'reinvite'
      post 'resend_invite'
      post 'resend_invite_to_all'
      post 'update_settings'
      post 'update_wants_message_reminder'
      post 'user_main_photo'
      post 'delete_activity'
      post 'delete_alert'
      post 'edit_photo'
      get 'active_trades'
      get 'my_wants'
      get 'wants_on_my_haves'

    end
    resources 'addresses'
    
    collection do
      get 'check_email'
    end
  end

  get 'users' => 'users#index'
  get 'users/pvt_msg_tab' => 'users#pvt_msg_tab'
  resources :browse, :controller => "items"
  match 'edit_profile' => 'users#edit_profile'
  match 'settings' => 'users#settings'





  # resources :home, :only => [:index]

  # controller :home do
  #   match :contest, :to => 'home#contest', :as => :contest, :via => :get
  #   match :contest_send_mail, :to=> 'home#contest_send_mail', :as => :contest_send_mail, :via => :post
  #   match :contest_share, :to=> 'home#contest_share', :as => :contest_share, :via => :post
  # end


  mount Split::Dashboard, :at => 'ab-tests'

  match 'reinvite' => 'users#reinvite', :via => :post
  # match 'reject_offer' => 'trades#reject_offer'
  match 'delete_user_photo' => 'common#delete_user_photo', :via => :post
  match 'delete_item_photo' => 'common#delete_item_photo', :via => :post
  match 'reply' => 'comments#reply', via: :post
  # match 'request_info' => 'common#request_info', :as => 'request_info'
  match 'thanks' => 'common#thanks'
  match 'change_location' => 'common#change_location'
  match 'auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'common#twitter_failure'
  match 'image_preview' => 'common#image_preview'
  match 'video_preview' => 'common#video_preview'
  match "password_reset" => "common#password_reset"
  match 'is_signed_in' => 'common#is_signed_in'
  match 'is_pub' => 'common#is_pub'
  match 'sign_in_success' => 'common#sign_in_success'
  match 'facebook_sign_in_success' => 'common#facebook_sign_in_success'
  match 'modals' => 'common#modals'
  match 'privacy_policy' => 'common#privacy_policy'
  match 'tandc' => 'common#tandc'
  match 'howthisworks' => 'common#howthisworks'
  match "password_changed" => "common#password_changed"
  match "after_sign_up" => "common#after_sign_up"
  match "after_sign_up_guest" => "common#after_sign_up_guest"
  match "after_change_password" => "common#after_change_password"
  match 'contact' => 'common#contact'
  match 'twitter_share_login' => 'common#twitter_share_login'
  match 'twitter_share' => 'common#twitter_share'
  match 'linkedin_login' => 'common#linkedin_login'
  match 'linkedin_share' => 'common#linkedin_share'
  match 'publink' => 'common#publink'
  match 'tradeya_expired' => 'items#tradeya_expired'
  match 'dead_link' => 'common#dead_link'
  match 'update_profile' => 'common#update_profile', :as => :update_profile
  match 'edit_user_image' => 'common#edit_user_image'
  match 'add_verification_success' => 'common#add_verification_success'
  match 'search_my_offer' => 'common#search_my_offer'
  match 'search_my_item_wants' => 'common#search_my_item_wants'
  match 'offer_data' => 'common#offer_data'
  match 'item_want_data' => 'common#item_want_data'
  match 'rotate_video' => 'common#rotate_video'
  match 'failure_network' => 'common#failure_network'
  # match 'at' => 'common#update_auth_token'

  match 'clear_all_cache' => 'common#clear_all_cache'
  match 'clear_item_cache' => 'items#clear_cache'
  match 'clear_category_cache' => 'common#clear_cache'
  match 'clear_home_cache' => 'home#clear_cache'
  match 'test_ad_tags' => 'home#test_ad_tags'
  match 'after_update_guest' => 'common#after_update_guest'

  match 'thumb_up_down/:v/:t' => 'thumb_up_downs#thumb_up_down'

  match "update_accept_offer_modal" => "accepted_offers#update_accept_offer_modal"
  match "accept_multiple_offers" => "accepted_offers#accept_multiple_offers", :via => :post

  match "items_distance" => "items#items_distance"
  match "search_by_zip" => "items#search_by_zip"
  match "complete_trade" => "items#complete_trade", :via => :post
  match 'postpone_trade' => 'items#postpone_trade', :via => :post
  match 'crop_image' => 'items#crop_image', :via => :post
  match 'update_user_categories' => 'profile#update_user_categories', :via => :post
  match 'thumbs_down_feedback' => 'thumb_up_downs#thumbs_down_add_reason', :via => :post

  match 'dashboard' => 'home#dashboard'
  match 'manage_tradeyas' => 'home#manage_tradeyas'
  match 'manage_offers' => 'home#manage_offers'
  match 'edit_settings' => 'home#edit_settings'
  match 'edit_verifications' => 'home#edit_verifications'
  match 'mark_alert_read_and_redirect' => 'home#mark_alert_read_and_redirect'
  match 'refresh_alert_count_and_show_new' => 'home#refresh_alert_count_and_show_new'

app/models/shared/attachment_helper.rb
module Shared
  module AttachmentHelper

    class << self
      def included(base)
        base.extend ClassMethods
      end
    end

    module ClassMethods
      def has_attachment(name, options = {})

        # generates a string containing the singular model name and the pluralized attachment name.
        # Examples: "user_avatars" or "asset_uploads" or "message_previews"
        attachment_owner    = self.table_name.singularize
        # attachment_folder   = "#{attachment_owner}_#{name.to_s.pluralize}"
        attachment_owner = ((attachment_owner == 'user_photo') ? 'user' : attachment_owner)
        attachment_folder = "/tradeya/#{attachment_owner}"

        # we want to create a path for the upload that looks like:
        # message_previews/00/11/22/001122deadbeef/thumbnail.png
        attachment_path     = "#{attachment_folder}/:id/:style/:filename"

        if Rails.env.production? or Rails.env.staging? or Rails.env.staging_20? # or Rails.env.development?
          options[:path]            ||= attachment_path
          options[:storage]         ||= :s3
          options[:s3_credentials]  ||= File.join(Rails.root, 'config', 'amazon_s3.yml')
          options[:s3_protocol]     ||= 'https'
        else
          # For local Dev/Test envs, use the default filesystem, but separate the environments
          # into different folders, so you can delete test files without breaking dev files.
          options[:path]  ||= ":rails_root/public/system/attachments/#{Rails.env}#{attachment_path}"
          options[:url]   ||= "/system/attachments/#{Rails.env}#{attachment_path}"
        end

        # pass things off to paperclip.
        has_attached_file name, options
      end
    end
  end
end

app/views/shared/_active_trades.html.erb
<div id="left_section_activity">
	<div class="recent_text"><img src="http://d3md9h2ro575fr.cloudfront.net/images/recent_clock.png"><a href="#">Recent</a></div>
	<% unless @recent_items.size == 0 %>	
		<ul class="recent_items_list">
				<% @recent_items.each do | item | %>
					<li><a href="<%= item[:url] %>"><%= item[:title] %></a></li>
				<% end %>
		</ul>
	<% end %>
	<div class="active_trade_text active"><a href="#"><img src="http://d3md9h2ro575fr.cloudfront.net/images/active_trade_icon.png">active trades</a></div>
	<ul class="active_trades_list">
		<!-- <li><a href="#">Beautiful Emerald N..<div class="active_trade_notify">5</div></a></li> -->
	</ul>
	<div class="wants_active_text"><%= link_to(raw('<img src="http://d3md9h2ro575fr.cloudfront.net/images/one_icon.png">wants'), my_wants_user_path, remote: true, :id => 'wants_header') %> </div>
	<ul class="my_wants_list">
		<li><%= link_to 'My Wants', my_wants_user_path, remote: true %></li>
		<li><%= link_to 'Wants on my haves', wants_on_my_haves_user_path, remote: true %></li>
	</ul>
	<div class="pending_active_text"><img src="http://d3md9h2ro575fr.cloudfront.net/images/pending_icon.png"><a href="#">pending</a></div>
</div>

<div id="right_section_activity">
	<div class="empty_active_trades">
		<div class="empty_activetrade_heading">You don’t have any activity to display yet...</div>
		<div class="empty_activetrade_btn1"><a href="#">Browse Popular Items</a></div>
		<div class="empty_activetrade_btn2"><a href="#">Connect With Friends</a></div>
		<div class="empty_activetrade_btn3"><a href="#">Post An Item</a></div>
	</div>

</div>	

<script>
// $(document).ready(function(){
// 	$('.wants_container').css('width','750px');
// 	$('.wants_container').css('position','relative');
// 	$('.wants_container').BlocksIt({
// 		numOfCol: 3,
// 		offsetX: 12,
// 		offsetY: 10,
// 		blockElement: '.user_wants_card'
// 	});
// 	$("img").one("load",function(){
// 		 $('.wants_container').BlocksIt({
// 				numOfCol: 3,
// 				offsetX: 12,
// 				offsetY: 10,
// 				blockElement: '.user_wants_card'
// 			});
// 	});
// 	$('.mywants_container').css('width','750px');
// 	$('.mywants_container').css('position','relative');
// 	$('.mywants_container').BlocksIt({
// 		numOfCol: 3,
// 		offsetX: 12,
// 		offsetY: 10,
// 		blockElement: '.user_wants_card'
// 	});
// 	$("img").one("load",function(){
// 		 $('.mywants_container').BlocksIt({
// 				numOfCol: 3,
// 				offsetX: 12,
// 				offsetY: 10,
// 				blockElement: '.user_wants_card'
// 			});
// 	});
// });
</script>

<%if @user.present?%>
<!--Content Start -->
<div class="container">
	<%if session[:have_saved]%>
		<script>
			$(function(){
      			$('#have_message_modal').modal("show");
   			});
		</script>
		<%session[:have_saved] = nil%>
	<%end%>
	<div class="span10 item_middle_section">
		<div class="center_content">
			<div class="dashboard_main_wrapper ">
				<% if params[:wanted_item] or params[:review_reminder] and flash[:error] or flash[:info]%>
					<div class="info_alert error_msg" id ="notice">
						<%wanted_item = Item.find_by_id(params[:wanted_item])%>
						<%if wanted_item.present? and wanted_item.deleted?%>
							<p>Whoops! Looks you have deleted "<%=wanted_item.title%>"! But, all is not lost. Check out <%=@user.title%>'s stuff to see if there's anything you want!</p>
						<%elsif wanted_item.present? and wanted_item.completed?%>
							<p>Whoops! Looks you already traded "<%=wanted_item.title%>"! But, all is not lost. Check out <%=@user.title%>'s stuff to see if there's anything you want!</p>
						<%elsif flash[:info] and params[:delete]%>
							<%delete_item = Item.find(params[:delete])%>
							<p><span class="msg_item_name">"<%=delete_item.title%>"</span> has been removed from your Haves Board</p>
						<%else%>
							<p><%= flash[:error] %></p>
						<%end%>
						<a href="#" class="info_cross" onclick="$('#notice').fadeOut(1000); return false;"><img src="http://d3md9h2ro575fr.cloudfront.net/images/info_cross.png"></a>
					</div>
				<% end %>
				
			</div>
			<!-- tab content start -->
			<div id="spinner" style="top: 90%; display: none"></div>
			<div class="tab-content" id="tab-content"></div>
			<!-- tab content ends -->
		</div>
	</div>
</div>
<!-- Content End-->
<%end%>

<script type="text/javascript">
	$('#wants-header').click(function () {
		$(".my_wants_list li:first").addClass('active');
	});

	$(document).ready(function(){
		$('#spinner').hide();
	});
	$('.profile_tabs li a').click(function(){
		$('.profile_tabs li').removeClass('active');
		$(this).parent().addClass('active');
		$("#reviews_tab_div").hide();
		$("#inbox_tab_div").hide();
		$("#inbox_options").hide();
		$(".reviews_by_user").addClass("active");

		$('#tab_haves').text("Haves");
		$('#tab_wants').text("Wants");
		$('#tab_likes').text("Likes");
		$('#tab_myoffers').text("My Offers");
		$('#tab_past_trades').text("Past Trades");
		$('#tab_reviews').text("Inbox");
		$('#tab_following').text("Friends");
	});
	// var opts = {
	// 	size: 75,           // Width and height of the spinner
	// 	factor: 0.25,       // Factor of thickness, density, etc.
	// 	color: "#FF5447",      // Color #rgb or #rrggbb
	// 	speed: 1.0,         // Number of turns per second
	// 	clockwise: true     // Direction of rotation
	// };
	// var ajaxLoader = new AjaxLoader("spinner", opts);
	$('#spinner').hide();
	$('.profile_tabs li:not("#tab_inbox") a').click(function(){
		$('#spinner').show();
		$('.tab_div_overlay').show();
	});

	$('.d_star_rating_large').raty({
			size:  '20',
			starOn:    'http://d3md9h2ro575fr.cloudfront.net/images/d_star_on.png',
			starOff:   'http://d3md9h2ro575fr.cloudfront.net/images/d_star_off.png',
			starHalf:   'http://d3md9h2ro575fr.cloudfront.net/images/half_color.png'
		});
	$('#d_overall_rating').raty({
		size:  '25',
		starOn:    'http://d3md9h2ro575fr.cloudfront.net/images/orangestar.png',
		starOff:   'http://d3md9h2ro575fr.cloudfront.net/images/whitestar.png',
		starHalf:   'http://d3md9h2ro575fr.cloudfront.net/images/half_color.png',
		halfShow: true,
		readOnly: true,
		score: <%=(@overall_rating.present?)? @overall_rating : 0%>
	});
	$('#d_item_described').raty({
		size:  '25',
		starOn:    'http://d3md9h2ro575fr.cloudfront.net/images/orangestar.png',
		starOff:   'http://d3md9h2ro575fr.cloudfront.net/images/whitestar.png',
		starHalf:   'http://d3md9h2ro575fr.cloudfront.net/images/half_color.png',
		halfShow: true,
		readOnly: true,
		score: <%=(@describe_rating.present?)? @describe_rating : 0%>
	});
	$('#d_item_communication').raty({
		size:  '25',
		starOn:    'http://d3md9h2ro575fr.cloudfront.net/images/orangestar.png',
		starOff:   'http://d3md9h2ro575fr.cloudfront.net/images/whitestar.png',
		starHalf:   'http://d3md9h2ro575fr.cloudfront.net/images/half_color.png',
		halfShow: true,
		readOnly: true,
		score: <%=(@communication_rating.present?)? @communication_rating : 0%>
	});

	// $('#my-offers-tab').click(function(){
	// 	$('#spinner').hide();
	// });
	$('#inbox-tab').click(function(){
		$('#spinner').hide();
		$('.tab_div_overlay').hide();
	});

	$(function(){
		<%if current_user and (@user == current_user)%>
      <%if @user.about != "" %>
  			$('.rating_text').css('box-shadow','none');
  		<%else%>
  			$('.rating_text').attr('style',"display: block;");
  		<%end%>
		<%else%>
  		$('.rating_text').css('box-shadow','none');
		<%end%>
	});

$('.active_trade_text').click(function(){
	$('.wants_on_my_haves').show();
	$('#active_trade_item').hide();
	$('.active_trade_text').addClass('active');
	$('.active_trades_list li').removeClass('active');
	$('.my_wants_list li').removeClass('active');
});
$('.my_wants_list li a').click(function(){
// 	$('.wants_on_my_haves').show();
// 	$('#active_trade_item').hide();
	$('.active_trade_text').removeClass('active');
	$('.active_trades_list li').removeClass('active');
	$('.my_wants_list li').removeClass('active');
	$(this).parent().addClass('active');
});
$('.active_trades_list li a').click(function(){
	$('.wants_on_my_haves').hide();
	$('#active_trade_item').show();
	$('.active_trades_list li').addClass('active');
	$('.active_trade_text').removeClass('active');
	$('.my_wants_list li').removeClass('active');
});
</script>

app/views/shared/_following_tab_facebook_friends.html.erb
<!-- Facebook Friends start -->
<%if @fb_friends_unfollowed.present? %>
<%@fb_friends_unfollowed.each do |fb_friend|%>
<%if fb_friend.present? %>
<div class="user_following_card">
  <div class="following_big_image">
    <a href="<%= user_path(fb_friend)%>" onclick="mixpanel.track('Click User Image on Following Card');_gaq.push(['_trackEvent', 'Following tab', 'clk_UsrImg_FllwngCard', 'Click User Image on Following Card']);addDelay(this,event); return false;"><img src="<%= fb_friend.user_image(:medium)%>" style="width: 225px;"></a>

  </div>
  <div class="following_heading_wrapper">
    <!-- Following Hover -->
    <%if current_user and fb_friend == current_user%>
    <%elsif current_user and @user == current_user%>
      <div class="follow_me follow_user_<%= fb_friend.id%>" id= "follow_div">
        <%= render 'shared/follow', :user => fb_friend %>
        <%#= form_tag follow_user_path(:id => fb_friend.id,:item_id => (@item)? @item.id : nil), :id => "follow_action", :remote=>true do %>
          <%#if current_user && !current_user.follows.where(:followed_id => fb_friend.id).blank?%>
            <%#= hidden_field_tag 'follow', false%>
            <%#= hidden_field_tag 'follow_tab', true%>
            <%#= hidden_field_tag 'follow_tab_facebook', true%>
            <!-- <p><a href="#"  onclick="$(this).parents('#follow_action').submit();mixpanel.track('UnFollow on Following Users Card');_gaq.push(['_trackEvent', 'Following card', 'Clk_Unfllw_FllwngCard', 'UnFollow on Following Users Card']); return false;">Unfollow</a></p> -->
          <%#else%>
            <%#= hidden_field_tag 'follow', true%>
            <%#= hidden_field_tag 'follow_tab', true%>
            <%#= hidden_field_tag 'follow_tab_facebook', true%>
            <!-- <p><a id="follow_<%= fb_friend.id%>"  href = "#" onclick="followUser('<%=fb_friend.id %>',this);mixpanel.track('Follow on Following Users Card');_gaq.push(['_trackEvent', 'Following card', 'Clk_Fllw_FllwngCard', 'Follow on Following Users Card']); return false;">Follow</a><p> -->
          <%#end%>
        <%#end%>
      </div>
    <%end%>

    <div class="follow_head_left">
      <p class="u_name"><a href="<%= user_path(fb_friend)%>"><%= fb_friend.title%></a></p>
      <p class="u_place"><%= fb_friend.location%></p>
    </div>
    <div class="star_section_right">
      <%= render 'shared/following_star_rating', :user => fb_friend%>
    </div>
  </div>

  <div class="following_thumbs_wrapper">
    <% fb_friend.items.limit(6).order("created_at DESC").where('status="LIVE"').each do |item|%>
      <div><%=link_to image_tag(item.item_image(:thumb)), item_path(item),:onclick=>"_gaq.push(['_trackEvent', 'Following Card', 'clk_ItmImg_FllwngCrd', 'Click Item Images on Following Tab']);mixpanel.track('Click Item Images on Following Tab'); addDelay(this,event); return false;" %></div>
      <%end%>
  </div>

  <div class="follow_shadow">
    <img src="http://d3md9h2ro575fr.cloudfront.net/images/follow_card_shadow.png">
  </div>
</div>
<%end%>
<%end%>
<%end%>


<%if @fb_friends_followed.present? %>
<%@fb_friends_followed.each do |fb_friend|%>
<%if fb_friend.present? %>
<div class="user_following_card">
  <div class="following_big_image">
    <a href="<%= user_path(fb_friend)%>" onclick="mixpanel.track('Click User Image on Following Card');_gaq.push(['_trackEvent', 'Following tab', 'clk_UsrImg_FllwngCard', 'Click User Image on Following Card']);addDelay(this,event); return false;"><img src="<%= fb_friend.user_image(:medium)%>" style="width: 225px;"></a>

  </div>
  <div class="following_heading_wrapper">
    <!-- Following Hover -->
    <%if current_user and fb_friend == current_user%>
    <%elsif current_user and @user == current_user%>
      <div class="follow_me follow_user_<%= fb_friend.id%>" id= "follow_div">
        <%= render 'shared/follow', :user => fb_friend %>
        <%#= form_tag follow_user_path(:id => fb_friend.id,:item_id => (@item)? @item.id : nil), :id => "follow_action", :remote=>true do %>
          <%#if current_user && !current_user.follows.where(:followed_id => fb_friend.id).blank?%>
            <%#= hidden_field_tag 'follow', false%>
            <%#= hidden_field_tag 'follow_tab', true%>
            <%#= hidden_field_tag 'follow_tab_facebook', true%>
            <!-- <p><a href="#"  onclick="$(this).parents('#follow_action').submit();mixpanel.track('UnFollow on Following Users Card');_gaq.push(['_trackEvent', 'Following card', 'Clk_Unfllw_FllwngCard', 'UnFollow on Following Users Card']); return false;">Unfollow</a></p> -->
          <%#else%>
            <%#= hidden_field_tag 'follow', true%>
            <%#= hidden_field_tag 'follow_tab', true%>
            <%#= hidden_field_tag 'follow_tab_facebook', true%>
            <!-- <p><a id="follow_<%= fb_friend.id%>"  href = "#" onclick="followUser('<%=fb_friend.id %>',this); return false;">Follow</a><p> -->
            <%#end%>
          <%#end%>
      </div>
    <%end%>

    <div class="follow_head_left">
      <p class="u_name"><a href="<%= user_path(fb_friend)%>"><%= fb_friend.title%></a></p>
      <p class="u_place"><%= fb_friend.location%></p>
    </div>
    <div class="star_section_right">
      <%= render 'shared/following_star_rating', :user => fb_friend%>
    </div>
  </div>

  <div class="following_thumbs_wrapper">
    <% fb_friend.items.limit(6).order("created_at DESC").where('status="LIVE"').each do |item|%>
      <div><%=link_to image_tag(item.item_image(:thumb)), item_path(item),:onclick=>"_gaq.push(['_trackEvent', 'Following Card', 'clk_ItmImg_FllwngCrd', 'Click Item Images on Following Tab']);mixpanel.track('Click Item Images on Following Tab');addDelay(this,event);return false;" %></div>
      <%end%>
  </div>

  <div class="follow_shadow">
    <img src="http://d3md9h2ro575fr.cloudfront.net/images/follow_card_shadow.png">
  </div>
</div>
<%end%>
<%end%>
<%end%>
<!-- Facebook Friends end -->
<script>
 $("#spinner").hide();
 $('.follow_tab_div_overlay').hide();
</script>
<script type="text/javascript">
 $(document).ready(function(){
   $(".follow_me").hide();
 });
 $(".user_following_card").hover(function(){
   $(this).find(".follow_me").show();
 },function(){
   $(".follow_me").hide();
 });
</script>