config/routes.rb
Tradeya::Application.routes.draw do


  resources :trade_communications


  resources :passive_trades do
    member do
      get :my_haves_tab
      get :communication_tab
      get :trader_haves_tab
    end
    resources :transactions
  end

  mount Resque::Server, :at => "/resque"

  # root :to => "home#index"
  root :to => "home#invite"
  # match 'invite' => 'home#invite'
  match 'friends_invite' => 'users#friends_invite'
  match 'home' => 'home#index'
  match 'trade_page' => 'items#trade_page'

  match 'welcome' => 'home#welcome'
  match 'holiday' => 'home#holiday'
  match 'getstarted' => 'home#getstarted'

  resources :accepted_offers, :only => [:create]
  resources :comments,:only => [:create,:destroy]
  resources :authentications
  resources :reviews

  # post 'charges/create'
  #post "charge_cards/create"
  resources :charge_cards, :only => [:index,:create,:destroy]
# mailboxer
  resources :conversations, :only => [:show] do
    member do
      post 'reply'
      get 'download'
      get 'displaytrash'
      get 'displayinbox'
      get 'trash'
      get 'markasunread'
      get 'markasread'
      get 'delete'
      get 'untrash'
      get 'newmsg'
    end
  end
  # match 'conversations/trash' => 'conversations#trash', via: [:post]

  resources :verify_phone_number do
    member { post 'twilio_hack' }
    member { post 'show' }
  end

  resources :trades do
    member do
      post :reject
      #   post :rate
      get :my_haves_tab
      get :communication_tab
      get :trader_haves_tab
      get :confirm
      post :complete
      get :accept_terms
      post :update
    end
    resources :transactions 
  end
  match "transactions/get_shipping" => "transactions#get_shipping"
   match "transactions/update_address" => "transactions#update_address"
   match "transactions/trade_review" => "transactions#trade_review"
   match "transactions/make_trade" => "transactions#make_trade"
  # Namespace for mobile api
  namespace :api, defaults:{format: 'json'} do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'
      end

      # items api calls
      get 'items' => 'items#index', :as => 'items'
      post 'items' => 'items#create'
      get 'items/:id' => 'items#show'
      post 'items/:id/likes' => 'items#likes'
      post 'items/:id/wants' => 'items#wants'
      post 'items/:id/haves' => 'items#haves'
      post 'items/:id/comment' => 'items#comment'

      get 'categories' => 'home#categories'

      # user profile api
      get 'users/:id' => 'users#show'
      get 'users/:id/likes' => 'users#likes'
      get 'users/:id/wants' => 'users#wants'
      get 'users/:id/haves' => 'users#haves'
      get 'users/:id/following' => 'users#followed_users'
      get 'users/:id/followers' => 'users#followers'
      post 'users/:id/follow' => 'users#follow'
      get 'users/:id/past_trades' => 'users#past_trades'
      post 'users/search' => 'users#search'
    end
  end

  ActiveAdmin.routes(self)
  devise_for :users,
  :controllers => {
    :registrations => 'registrations',
    :passwords => 'passwords',
    :sessions => 'sessions',
    :confirmations => 'confirmation'}
    # :invitations => 'invitations'}

  devise_scope :user do
    match 'failure' => 'sessions#failure'
    match 'update_zip' => 'registrations#update_zip', :as => :update_zip
    match 'update_account_settings' => 'registrations#update_account_settings', :as => :update_account_settings
    match 'change_user_password' => 'registrations#change_user_password', :as => :change_user_password
    match 'deactivate_account' => 'registrations#deactivate_account', :as => :deactivate_account
    match 'create_guest' => 'registrations#create_guest', :as => :create_guest, :via => :post
    match 'update_guest' => 'registrations#update_guest', :as => :update_guest, :via => :post
    match 'guest_deactivate_account' => 'registrations#guest_deactivate_account', :as => :guest_deactivate_account
  end

  # resources :items, :only => [:create, :show, :new]
  resources :items do
    member do
      post 'like'
      post 'haves'
      post 'wants'
      get 'trade_offers'
      get 'my_offers'
      get 'accepted_offers'
      get 'rejected_offers'
      get 'wants_detail'
      post 'remove_have'
      post 'remove_offer'
      post 'want_cancel'
      post 'main_photo'
      post 'request_info'
      post 'edit_photo'
    end
  end

  resources :users, :only => [:show, :edit, :update] do
    member do
      post 'follow'
      get 'dashboard'
      get 'wants'
      get 'haves'
      get 'likes'
      get 'reviews'
      get 'following'
      get 'followers'
      get 'facebook_friends'
      get 'twitter_friends'
      get 'following_tab_search'
      get 'past_trades'
      get 'myoffers'
      get 'activity_feed'
      get 'inbox'
      post 'inbox'
      get 'sort_review'
      get 'settings'
      get 'invite'
      get 'pvt_msg_tab'
      get 'messaging'
      # get 'notifications'
      get 'inbox/messaging'
      get 'inbox/notifications'
      # post 'reinvite'
      post 'resend_invite'
      post 'resend_invite_to_all'
      post 'update_settings'
      post 'update_wants_message_reminder'
      post 'user_main_photo'
      post 'delete_activity'
      post 'delete_alert'
      post 'edit_photo'
      get 'active_trades'
      get 'my_wants'
      get 'wants_on_my_haves'

    end
    resources 'addresses'
    
    collection do
      get 'check_email'
    end
  end

  get 'users' => 'users#index'
  get 'users/pvt_msg_tab' => 'users#pvt_msg_tab'
  resources :browse, :controller => "items"
  match 'edit_profile' => 'users#edit_profile'
  match 'settings' => 'users#settings'





  # resources :home, :only => [:index]

  # controller :home do
  #   match :contest, :to => 'home#contest', :as => :contest, :via => :get
  #   match :contest_send_mail, :to=> 'home#contest_send_mail', :as => :contest_send_mail, :via => :post
  #   match :contest_share, :to=> 'home#contest_share', :as => :contest_share, :via => :post
  # end


  mount Split::Dashboard, :at => 'ab-tests'

  match 'reinvite' => 'users#reinvite', :via => :post
  # match 'reject_offer' => 'trades#reject_offer'
  match 'delete_user_photo' => 'common#delete_user_photo', :via => :post
  match 'delete_item_photo' => 'common#delete_item_photo', :via => :post
  match 'reply' => 'comments#reply', via: :post
  # match 'request_info' => 'common#request_info', :as => 'request_info'
  match 'thanks' => 'common#thanks'
  match 'change_location' => 'common#change_location'
  match 'auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'common#twitter_failure'
  match 'image_preview' => 'common#image_preview'
  match 'video_preview' => 'common#video_preview'
  match "password_reset" => "common#password_reset"
  match 'is_signed_in' => 'common#is_signed_in'
  match 'is_pub' => 'common#is_pub'
  match 'sign_in_success' => 'common#sign_in_success'
  match 'facebook_sign_in_success' => 'common#facebook_sign_in_success'
  match 'modals' => 'common#modals'
  match 'privacy_policy' => 'common#privacy_policy'
  match 'tandc' => 'common#tandc'
  match 'howthisworks' => 'common#howthisworks'
  match "password_changed" => "common#password_changed"
  match "after_sign_up" => "common#after_sign_up"
  match "after_sign_up_guest" => "common#after_sign_up_guest"
  match "after_change_password" => "common#after_change_password"
  match 'contact' => 'common#contact'
  match 'twitter_share_login' => 'common#twitter_share_login'
  match 'twitter_share' => 'common#twitter_share'
  match 'linkedin_login' => 'common#linkedin_login'
  match 'linkedin_share' => 'common#linkedin_share'
  match 'publink' => 'common#publink'
  match 'tradeya_expired' => 'items#tradeya_expired'
  match 'dead_link' => 'common#dead_link'
  match 'update_profile' => 'common#update_profile', :as => :update_profile
  match 'edit_user_image' => 'common#edit_user_image'
  match 'add_verification_success' => 'common#add_verification_success'
  match 'search_my_offer' => 'common#search_my_offer'
  match 'search_my_item_wants' => 'common#search_my_item_wants'
  match 'offer_data' => 'common#offer_data'
  match 'item_want_data' => 'common#item_want_data'
  match 'rotate_video' => 'common#rotate_video'
  match 'failure_network' => 'common#failure_network'
  # match 'at' => 'common#update_auth_token'

  match 'clear_all_cache' => 'common#clear_all_cache'
  match 'clear_item_cache' => 'items#clear_cache'
  match 'clear_category_cache' => 'common#clear_cache'
  match 'clear_home_cache' => 'home#clear_cache'
  match 'test_ad_tags' => 'home#test_ad_tags'
  match 'after_update_guest' => 'common#after_update_guest'

  match 'thumb_up_down/:v/:t' => 'thumb_up_downs#thumb_up_down'

  match "update_accept_offer_modal" => "accepted_offers#update_accept_offer_modal"
  match "accept_multiple_offers" => "accepted_offers#accept_multiple_offers", :via => :post

  match "items_distance" => "items#items_distance"
  match "search_by_zip" => "items#search_by_zip"
  match "complete_trade" => "items#complete_trade", :via => :post
  match 'postpone_trade' => 'items#postpone_trade', :via => :post
  match 'crop_image' => 'items#crop_image', :via => :post
  match 'update_user_categories' => 'profile#update_user_categories', :via => :post
  match 'thumbs_down_feedback' => 'thumb_up_downs#thumbs_down_add_reason', :via => :post

  match 'dashboard' => 'home#dashboard'
  match 'manage_tradeyas' => 'home#manage_tradeyas'
  match 'manage_offers' => 'home#manage_offers'
  match 'edit_settings' => 'home#edit_settings'
  match 'edit_verifications' => 'home#edit_verifications'
  match 'mark_alert_read_and_redirect' => 'home#mark_alert_read_and_redirect'
  match 'refresh_alert_count_and_show_new' => 'home#refresh_alert_count_and_show_new'

app/controllers/api/v1/home_controller.rb
class Api::V1::HomeController < ApplicationController
  skip_before_filter :check_route
  skip_before_filter :verify_authenticity_token,
  :if => Proc.new { |c| c.request.format == 'application/json' }

  before_filter :authenticate_user_from_token!, :except => [:categories]
  respond_to :json

  def categories
    @goods = Category.goods
    @services = Category.services
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def alert_url(alert)
    item = (alert.item.nil? ? alert.trade.item : alert.item)

    if alert.is_new
      return "/mark_alert_read_and_redirect?id=" + alert.id.to_s + "&redirect_url=" + URI.encode(item_path(item))
    else
      return item_path(item)
    end
  end
end

app/views/home/_category_tradeyas.html.erb
<% counter = 6 %>
<% @tradeyas_by_category.each do |item| %>
	<div class="tycarousel_complete">
		<table width="100%">
			<tr valign="top">
				<td colspan="2">
					<div class="item_title" style="padding-top: 0px;"><a class='click' href="<%= item.item_url %>" onclick="/*_kmq.push(['record', 'TryaLnkLdngPg',{ 'SignedIn' : get_KMSignedIn()}]);*/"><%= truncate(item.item_title, :length => 72) %></a></div>
					<div class="service" style="padding-bottom: 18px;"><%= item.category_title %></div>
				</td>
			</tr>
		</table>
		<table width="100%">
			<tr valign="top">
				<td rowspan="2" valign="middle" class="user_image_border" style="width: 340px; height: 256px; text-align: center; background-color: #fff;">
					<% if not item.item_videos[0].nil? %>
						<div class="item_image">
							<a href="#" onclick="return false;" style="display:block;width:338px;height:251px;vertical-align: middle;" id="itemPlayerCatTrd_<%= counter %>"></a>
						</div>
					<% else %>
						<div class="item_image">
							<img src="<%= item.item_image(:large) %>" style="vertical-align: middle;" />
						</div>
					<% end %>
				</td>
				<td style="width: 110px;padding-left: 16px;">
					<div class="user_image user_image_border" style="margin-bottom: 15px;"><img src="<%= item.user.user_image(:thumb) %>"<%= (item.user.isFacebookUser? ? ' width=100px' : "") %> /></div>
					<div class="user_name"><%= item.user.title %></div>
					<div class="user_city"><%= item.user.location %></div>
				</td>
				<td>
					<div class="item_desc_cat"><%= auto_link(truncate(item.desc, :length => 140, :omission => '').strip + '<a class="click" href="' + item.item_url + '"><img class="item_desc_img" src="https://s3.amazonaws.com/tradeya_prod/tradeya/images/ellipses.png" /></a>', :html => { :target => '_blank' }) %></div>
				</td>
			</tr>
			<tr>
				<td colspan="3" style="padding-left: 16px;">
					<div class="dot_line" style="margin-top: -8px;"><img src="https://s3.amazonaws.com/tradeya_prod/tradeya/images/dottedline.png" /></div>
					<div class="cat_desc">
						<a class='click' href='<%=items_path%>?category=<%=@current_category.id%>' >see more <%=@current_category.name%> TradeYas</a>
					</div>
				</td>
			</tr>
		</table>
		<% if not item.item_videos[0].nil? %>
			<script>$(function(){playVideo('itemPlayerCatTrd_<%= counter %>', '<%= item.item_videos[0].video %>', false, 'tradeyacarousel');});</script>
		<% end %>
	</div>
	<% counter += 1 %>
<% end %>

app/views/home/_user_current_tradeyas.html.erb
<% if @current_tradeyas and @current_tradeyas.count > 0 %>
<!-- Tool Tip Icon-->
<% if current_user and current_user.tooltip %>
	<div class="info_tip_icon" style = "margin-left: 248px;"><a href="#" onclick="return false;"><img src="https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/info_tip_icon.png" onmouseover="current_tradeya_tooltip_show();"  onmouseout="current_tradeya_tooltip_hide();" onclick="/*_kmq.push(['record', 'dashboard currenttradeyas tooltip for your current tradeyas',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'tooltip_currenttradeyas', 'Activate Tooltip Next to Your Current TradeYas in Dashboard']);*/" /></a></div>
<% end %>
<!--  -->
<table width="100%" class="user_current_tradeyas">
	<% counter = 1 %>
	<% timer_tool_tip = 0 %>
	<% @current_tradeyas.each_with_index do |item, index| %>
		<tr valign="top" style="height: 80px;">
			<td width="10%">
				<% if index == 0 %>
						<div class="tooltip_post current_tradeyas_tooltip" style = "margin-left: -160px; margin-top: -30px;"><img src=<%= getToolTipImage(TOOL_TIP_NEW_TRADEYA) %> /></div>
						<div class="tooltip_post current_tradeyas_tooltip_right" style = "margin-left: 58px; margin-top: -30px;"><img src=<%= getToolTipImage(TOOL_TIP_NEW_TRADEYA_RIGHT) %> /></div>
				<% end %>
				<% if not item.item_photos[0].nil? %>
					<div class="alert_img user_image_border" style="text-align: center"><img src="<%= item.item_image(:small) %>" /></div>
				<% elsif not item.item_videos[0].nil? %>
					<a href="<%= item.item_url %>"><div style="position:absolute;height:52px;width:72px;filter:alpha(opacity=60);-moz-opacity: 0.6;opacity: 0.6;"></div></a>
					<div class="alert_img user_image_border" id="item_video<%= item.id %>"></div>
					<script>$(function(){videoAsRedirect('item_video<%= item.id %>', '<%= item.item_videos[0].video %>','<%= item.item_url %>');});</script>
				<% else %>
					<div class="alert_img user_image_border" style="text-align: center"><img src="https://s3.amazonaws.com/tradeya_prod/tradeya/images/default_img.png" /></div>
				<% end %>
			</td>
			<td width="56%">
				<div class="current_trd_title"><a class = 'click' href="<%= item.item_url %>" onclick="/*_kmq.push(['record', 'dashboard currenttradeyas body link tradya title',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_TryaLnkLdnPg', 'Click on Any TradeYa title in Manage TradeYas of Dashboard']);*/"><%= item.item_title %></a></div>
				<div class="current_trd_btns">
					<ul class="current_trd_btns_ul">
						<% if item.trades.count == 0 %>
							<li style="margin-top: 1px;"><a class='click' href="<%= edit_item_path(item) %>" onclick="/*_kmq.push(['record', 'dashboard currenttradeyas body button edit',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_editTradeYa', 'Click on Edit button for TradeYa created from Offer']);*/"><img src="https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/edit_button.png" onmouseover="this.src='https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/edit_button_roll.png'" onmouseout="this.src='https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/edit_button.png'" /></a></li>
						<% end %>
						<li>
							<% if index == 1 %>
								<div class="tooltip_post current_tradeyas_tooltip" style = "margin-left: -160px; margin-top: -25px;"><img src=<%= getToolTipImage(TOOL_TIP_SPREAD_THE_WORD) %> /></div>
								<div class="tooltip_post current_tradeyas_tooltip_right" style = "margin-left: 102px; margin-top: -25px;"><img src=<%= getToolTipImage(TOOL_TIP_SPREAD_THE_WORD_RIGHT) %> /></div>
							<% end %>
							<a href="#" class='position-click' onclick="/*_kmq.push(['record', 'dashboard currenttradeyas body button share with friends',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_PrmtNowBtn', 'Click on Share with Friends!']);*/ return false;"><img src="https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/share_manage.png" onmouseover="this.src='https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/share_manage_roll.png'" onmouseout="this.src='https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/share_manage.png'" onclick="return openPromoteNowPopup(<%= item.id %>);" /></a></li>
						<li style="margin-top: 1px;">
							<% if index == 0 %>
								<div class="tooltip_post current_tradeyas_tooltip" style = "margin-left: -160px; margin-top: -25px;"><img src=<%= getToolTipImage(TOOL_TIP_POSTPONE_TRADEYA) %> /></div>
								<div class="tooltip_post current_tradeyas_tooltip_right" style = "margin-left: 104px; margin-top: -25px;"><img src=<%= getToolTipImage(TOOL_TIP_POSTPONE_TRADEYA_RIGHT) %> /></div>
							<% end %>
							<a href="#" class='position-click' onclick="/*_kmq.push(['record', 'dashboard currenttradeyas body button postpone',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_PostponeTradeya', 'Click on Postpone TradeYa button']);*/ return false;"><img src="https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/postpone_button.png" onmouseover="this.src='https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/postpone_button_roll.png'" onmouseout="this.src='https://s3.amazonaws.com/tradeya_stg_2/tradeya/images/postpone_button.png'" onclick="$('#post_trd_id').val(<%= item.id %>); $('#post_trd').modal('show');" /></a>
						</li>
					</ul>
				</div>
			</td>
			<td width="8%">
				<div class="current_trd_comment">Comments</div>
				<div class="comment_count"><%= item.comments_by_others %></div>
			</td>
			<td width="8%">
				<div class="current_trd_offer">Offers</div>
				<div class="offer_count"><%= item.trades.count %></div>
			</td>
			<td width="20%">
			</td>
		</tr>
		<% counter += 1 %>
	<% end %>
</table>
<% else %>
	<!-- If no Tradeyas Present -->
	<div class="user_no_tradeyas">You have <b>no</b> active TradeYas. Do you want to <a class="click" href="<%= new_item_path %>">submit a TradeYa?</a> </div>
<% end %>
<!-- for postponing tradeya -->
<input type="hidden" id="post_trd_id">
<script>
	$(document).ready(function() {
		bindAjaxSpinner();
	});
</script>

app/views/home/_usr_detail_dashboard.html.erb
<div class="dash_user_name"><%= current_user.title %> <span class="dash_user_edit"><a href="#" onclick="$('#usr_profile_info').modal('show'); /*_kmq.push(['record', 'dashboard sidenav link edit profilename',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_editprofilename', 'Edit Profile Name in Dashboard']);*/">edit</a></span></div>
<div class="dash_user_city">in <%= current_user.location %></div>
<% if @user_tradeyas_count > 0 %>
	<% if isMozilla? %>
		<div class="see_all_user_trd" style="margin-top: 7px;"><a href='<%= items_url %>?u=<%=current_user.id %>' onclick="/*_kmq.push(['record', 'dashboard sidenav link seealltradeyas',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_seealltrades', 'See All TradeYas text link in Dashboard']);*/">See <%= @user_tradeyas_count == 1 ? '' : 'all' %> <%= @user_tradeyas_count %> <%= @user_tradeyas_count == 1 ? '' : 'of' %> <%= current_user.first_name_with_s %> TradeYas</a></div>
	<% else %>
		<div class="see_all_user_trd"><a href='<%= items_url %>?u=<%=current_user.id %>' onclick="/*_kmq.push(['record', 'dashboard sidenav link seealltradeyas',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_seealltrades', 'See All TradeYas text link in Dashboard']);*/">See <%= @user_tradeyas_count == 1 ? '' : 'all' %> <%= @user_tradeyas_count %> <%= @user_tradeyas_count == 1 ? '' : 'of' %> <%= current_user.first_name_with_s %> TradeYas</a></div>
	<% end  %>
<% end %>
<% if current_user.goods_sub_cat_ids.blank? and current_user.services_sub_cat_ids.blank? and current_user.interests_sub_cat_ids.blank? and (current_user.wish.blank? or current_user.wish.nil?) %>
	<% if isMozilla? %>
		<div class="empty_bio" style="padding-bottom: 8px">
	<% else %>
		<div class="empty_bio">
	<% end  %>

	Oh noes! It looks like your profile bio is empty, but that could change if you <% if not current_user.is_guest_user then %> <a href="<%= profile_url %>" onclick="/*_kmq.push(['record', 'dashboard sidenav link onboardingquiz',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_OnboardLdnPg', 'Onboarding Text Link in Dashboard']);*/">tell us about yourself</a><% else %><a href="#" onclick="return guest_user_final_signup();">upgrade to an official account</a><% end %>.
</div>
<% else %>
<% if isMozilla? %>
	<div class="dash_user_abt" style="margin-top: 13px; padding-left: 1px;">
<% else %>
	<div class="dash_user_abt" style="margin-top: 15px">
<% end  %>
	My Wish <span class="dash_user_edit"><a href="<%= profile_url + '?step=3&edit=true' %>" onclick="/*_kmq.push(['record', 'dashboard sidenav link edit mywish',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_Onboardstep3', 'Edit My Wish for Onboarding in Dashboard']);*/">edit</a></span>
</div>
<% if isMozilla? %>
	<div class="dash_usr_abt_detail" style="padding-left: 1px;">
<% else %>
	<div class="dash_usr_abt_detail">
<% end  %>
	<%= current_user.wish %>
</div>

<div class="dash_user_abt" style="margin-top: 21px">Goods I Want <span class="dash_user_edit"><a href="<%= profile_url + '?step=1&edit=true' %>" onclick="/*_kmq.push(['record', 'dashboard sidenav link edit goodsIwant',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_Onboardstep1', 'Edit Goods I Want for Onboarding in Dashboard']);*/">edit</a></span></div>
<% if isMozilla? %>
	<div class="dash_usr_abt_detail" style="padding-left: 1px;">
<% else %>
	<div class="dash_usr_abt_detail">
<% end  %>
	<%= current_user.goods %>
</div>

<% if isMozilla? %>
	<div class="dash_user_abt" style="margin-top: 18px; padding-left: 1px;">
<% else %>
	<div class="dash_user_abt" style="margin-top: 20px">
<% end  %>
Services I Want <span class="dash_user_edit"><a href="<%= profile_url + '?step=2&edit=true' %>" onclick="/*_kmq.push(['record', 'dashboard sidenav link edit servicesIwant',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_Onboardstep2', 'Edit Services I Want for Onboarding in Dashboard']);*/">edit</a></span></div>
<% if isMozilla? %>
	<div class="dash_usr_abt_detail" style="padding-left: 1px;">
<% else %>
	<div class="dash_usr_abt_detail">
<% end  %>
	<%= current_user.services %>
</div>

<% if isMozilla? %>
	<div class="dash_user_abt" style="margin-top: 20px; padding-left: 1px;">
<% else %>
	<div class="dash_user_abt" style="margin-top: 22px">
<% end  %>
My Interests <span class="dash_user_edit"><a href="<%= profile_url + '?step=3&edit=true' %>" onclick="/*_kmq.push(['record', 'dashboard sidenav link edit myInterests',{ 'SignedIn' : get_KMSignedIn()}]);_gaq.push(['_trackEvent', 'dashboard', 'Clk_Onboardstep3', 'Edit My Interests for Onboarding in Dashboard']);*/">edit</a></span></div>
<% if isMozilla? %>
	<div class="dash_usr_abt_detail" style="padding-left: 1px;">
<% else %>
	<div class="dash_usr_abt_detail">
<% end  %>
	<%= current_user.interests %>
</div>
<% end %>

<!-- <div class="dash_user_abt">About Me</div>
<div id = "user_about_me" class="dash_user_det_short">
	<%# if current_user.about.nil? || current_user.about.blank? %>
		<div>Write a little something about yourself!</div>
	<% #else %>	
	<div id="user_about-less"><%= current_user.about.slice(0..49).to_s.gsub(/(?:\n\r?|\r\n?)/, '<br>').html_safe %> </div>
	<%# if current_user.about.size > 50 %>
		<div id="user-about-more" style="display:none;"><%= current_user.about.slice(50..-1).to_s.gsub(/(?:\n\r?|\r\n?)/, '<br>').html_safe %></div>
		<a id ="show-more-less" href="#" onclick="return aboutMe();" class="read_more">read more >></a>
	<%# end %>
<%# end %>
</div> -->