config/routes.rb
Tradeya::Application.routes.draw do


  resources :trade_communications


  resources :passive_trades do
    member do
      get :my_haves_tab
      get :communication_tab
      get :trader_haves_tab
    end
    resources :transactions
  end

  mount Resque::Server, :at => "/resque"

  # root :to => "home#index"
  root :to => "home#invite"
  # match 'invite' => 'home#invite'
  match 'friends_invite' => 'users#friends_invite'
  match 'home' => 'home#index'
  match 'trade_page' => 'items#trade_page'

  match 'welcome' => 'home#welcome'
  match 'holiday' => 'home#holiday'
  match 'getstarted' => 'home#getstarted'

  resources :accepted_offers, :only => [:create]
  resources :comments,:only => [:create,:destroy]
  resources :authentications
  resources :reviews

  # post 'charges/create'
  #post "charge_cards/create"
  resources :charge_cards, :only => [:index,:create,:destroy]
# mailboxer
  resources :conversations, :only => [:show] do
    member do
      post 'reply'
      get 'download'
      get 'displaytrash'
      get 'displayinbox'
      get 'trash'
      get 'markasunread'
      get 'markasread'
      get 'delete'
      get 'untrash'
      get 'newmsg'
    end
  end
  # match 'conversations/trash' => 'conversations#trash', via: [:post]

  resources :verify_phone_number do
    member { post 'twilio_hack' }
    member { post 'show' }
  end

  resources :trades do
    member do
      post :reject
      #   post :rate
      get :my_haves_tab
      get :communication_tab
      get :trader_haves_tab
      get :confirm
      post :complete
      get :accept_terms
      post :update
    end
    resources :transactions 
  end
  match "transactions/get_shipping" => "transactions#get_shipping"
   match "transactions/update_address" => "transactions#update_address"
   match "transactions/trade_review" => "transactions#trade_review"
   match "transactions/make_trade" => "transactions#make_trade"
  # Namespace for mobile api
  namespace :api, defaults:{format: 'json'} do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'
      end

      # items api calls
      get 'items' => 'items#index', :as => 'items'
      post 'items' => 'items#create'
      get 'items/:id' => 'items#show'
      post 'items/:id/likes' => 'items#likes'
      post 'items/:id/wants' => 'items#wants'
      post 'items/:id/haves' => 'items#haves'
      post 'items/:id/comment' => 'items#comment'

      get 'categories' => 'home#categories'

      # user profile api
      get 'users/:id' => 'users#show'
      get 'users/:id/likes' => 'users#likes'
      get 'users/:id/wants' => 'users#wants'
      get 'users/:id/haves' => 'users#haves'
      get 'users/:id/following' => 'users#followed_users'
      get 'users/:id/followers' => 'users#followers'
      post 'users/:id/follow' => 'users#follow'
      get 'users/:id/past_trades' => 'users#past_trades'
      post 'users/search' => 'users#search'
    end
  end

  ActiveAdmin.routes(self)
  devise_for :users,
  :controllers => {
    :registrations => 'registrations',
    :passwords => 'passwords',
    :sessions => 'sessions',
    :confirmations => 'confirmation'}
    # :invitations => 'invitations'}

  devise_scope :user do
    match 'failure' => 'sessions#failure'
    match 'update_zip' => 'registrations#update_zip', :as => :update_zip
    match 'update_account_settings' => 'registrations#update_account_settings', :as => :update_account_settings
    match 'change_user_password' => 'registrations#change_user_password', :as => :change_user_password
    match 'deactivate_account' => 'registrations#deactivate_account', :as => :deactivate_account
    match 'create_guest' => 'registrations#create_guest', :as => :create_guest, :via => :post
    match 'update_guest' => 'registrations#update_guest', :as => :update_guest, :via => :post
    match 'guest_deactivate_account' => 'registrations#guest_deactivate_account', :as => :guest_deactivate_account
  end

  # resources :items, :only => [:create, :show, :new]
  resources :items do
    member do
      post 'like'
      post 'haves'
      post 'wants'
      get 'trade_offers'
      get 'my_offers'
      get 'accepted_offers'
      get 'rejected_offers'
      get 'wants_detail'
      post 'remove_have'
      post 'remove_offer'
      post 'want_cancel'
      post 'main_photo'
      post 'request_info'
      post 'edit_photo'
    end
  end

  resources :users, :only => [:show, :edit, :update] do
    member do
      post 'follow'
      get 'dashboard'
      get 'wants'
      get 'haves'
      get 'likes'
      get 'reviews'
      get 'following'
      get 'followers'
      get 'facebook_friends'
      get 'twitter_friends'
      get 'following_tab_search'
      get 'past_trades'
      get 'myoffers'
      get 'activity_feed'
      get 'inbox'
      post 'inbox'
      get 'sort_review'
      get 'settings'
      get 'invite'
      get 'pvt_msg_tab'
      get 'messaging'
      # get 'notifications'
      get 'inbox/messaging'
      get 'inbox/notifications'
      # post 'reinvite'
      post 'resend_invite'
      post 'resend_invite_to_all'
      post 'update_settings'
      post 'update_wants_message_reminder'
      post 'user_main_photo'
      post 'delete_activity'
      post 'delete_alert'
      post 'edit_photo'
      get 'active_trades'
      get 'my_wants'
      get 'wants_on_my_haves'

    end
    resources 'addresses'
    
    collection do
      get 'check_email'
    end
  end

  get 'users' => 'users#index'
  get 'users/pvt_msg_tab' => 'users#pvt_msg_tab'
  resources :browse, :controller => "items"
  match 'edit_profile' => 'users#edit_profile'
  match 'settings' => 'users#settings'





  # resources :home, :only => [:index]

  # controller :home do
  #   match :contest, :to => 'home#contest', :as => :contest, :via => :get
  #   match :contest_send_mail, :to=> 'home#contest_send_mail', :as => :contest_send_mail, :via => :post
  #   match :contest_share, :to=> 'home#contest_share', :as => :contest_share, :via => :post
  # end


  mount Split::Dashboard, :at => 'ab-tests'

  match 'reinvite' => 'users#reinvite', :via => :post
  # match 'reject_offer' => 'trades#reject_offer'
  match 'delete_user_photo' => 'common#delete_user_photo', :via => :post
  match 'delete_item_photo' => 'common#delete_item_photo', :via => :post
  match 'reply' => 'comments#reply', via: :post
  # match 'request_info' => 'common#request_info', :as => 'request_info'
  match 'thanks' => 'common#thanks'
  match 'change_location' => 'common#change_location'
  match 'auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'common#twitter_failure'
  match 'image_preview' => 'common#image_preview'
  match 'video_preview' => 'common#video_preview'
  match "password_reset" => "common#password_reset"
  match 'is_signed_in' => 'common#is_signed_in'
  match 'is_pub' => 'common#is_pub'
  match 'sign_in_success' => 'common#sign_in_success'
  match 'facebook_sign_in_success' => 'common#facebook_sign_in_success'
  match 'modals' => 'common#modals'
  match 'privacy_policy' => 'common#privacy_policy'
  match 'tandc' => 'common#tandc'
  match 'howthisworks' => 'common#howthisworks'
  match "password_changed" => "common#password_changed"
  match "after_sign_up" => "common#after_sign_up"
  match "after_sign_up_guest" => "common#after_sign_up_guest"
  match "after_change_password" => "common#after_change_password"
  match 'contact' => 'common#contact'
  match 'twitter_share_login' => 'common#twitter_share_login'
  match 'twitter_share' => 'common#twitter_share'
  match 'linkedin_login' => 'common#linkedin_login'
  match 'linkedin_share' => 'common#linkedin_share'
  match 'publink' => 'common#publink'
  match 'tradeya_expired' => 'items#tradeya_expired'
  match 'dead_link' => 'common#dead_link'
  match 'update_profile' => 'common#update_profile', :as => :update_profile
  match 'edit_user_image' => 'common#edit_user_image'
  match 'add_verification_success' => 'common#add_verification_success'
  match 'search_my_offer' => 'common#search_my_offer'
  match 'search_my_item_wants' => 'common#search_my_item_wants'
  match 'offer_data' => 'common#offer_data'
  match 'item_want_data' => 'common#item_want_data'
  match 'rotate_video' => 'common#rotate_video'
  match 'failure_network' => 'common#failure_network'
  # match 'at' => 'common#update_auth_token'

  match 'clear_all_cache' => 'common#clear_all_cache'
  match 'clear_item_cache' => 'items#clear_cache'
  match 'clear_category_cache' => 'common#clear_cache'
  match 'clear_home_cache' => 'home#clear_cache'
  match 'test_ad_tags' => 'home#test_ad_tags'
  match 'after_update_guest' => 'common#after_update_guest'

  match 'thumb_up_down/:v/:t' => 'thumb_up_downs#thumb_up_down'

  match "update_accept_offer_modal" => "accepted_offers#update_accept_offer_modal"
  match "accept_multiple_offers" => "accepted_offers#accept_multiple_offers", :via => :post

  match "items_distance" => "items#items_distance"
  match "search_by_zip" => "items#search_by_zip"
  match "complete_trade" => "items#complete_trade", :via => :post
  match 'postpone_trade' => 'items#postpone_trade', :via => :post
  match 'crop_image' => 'items#crop_image', :via => :post
  match 'update_user_categories' => 'profile#update_user_categories', :via => :post
  match 'thumbs_down_feedback' => 'thumb_up_downs#thumbs_down_add_reason', :via => :post

  match 'dashboard' => 'home#dashboard'
  match 'manage_tradeyas' => 'home#manage_tradeyas'
  match 'manage_offers' => 'home#manage_offers'
  match 'edit_settings' => 'home#edit_settings'
  match 'edit_verifications' => 'home#edit_verifications'
  match 'mark_alert_read_and_redirect' => 'home#mark_alert_read_and_redirect'
  match 'refresh_alert_count_and_show_new' => 'home#refresh_alert_count_and_show_new'

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/partials/_payment_details.html.erb
<div class="transaction_detail_div payment_div">
  <div class="transaction_heading payment_heading">
    <div class="heading_tick"><img src="http://d3md9h2ro575fr.cloudfront.net/images/tick_orange.png"></div>
    3. Payment
    <div class="tr_edit_btn">
     <%= form_tag charge_cards_path, :id => "stripe-form-tag", :remote => true do %>
    <a id="add_card" href="#" onclick="return false;">Add</a><% end %></div>
    
    <div class="tr_edit_btn">
    <a href="#" id="edit_cards" onclick="return false;">Edit</a>
  </div>
  </div>
  
  

  <!-- Step3 Form Start -->
<!--   <form class="form-horizontal form_step3">
    <div class="transaction_payment">
      <div class="edit_login_text">Payment Method</div>
      <hr class="password_control_group" />
      <div class="control-group">
        <div class="controls">
          <label class="radio credit_card">
            <input type="radio" name="cardtype" /><label>Credit Card</label>
          </label>
          <label class="radio credit_card">
            <input type="radio" name="cardtype" /><label><img src="http://d3md9h2ro575fr.cloudfront.net/images/paypalicon.png" style="margin-top: -12px;"></label>
          </label>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputlname">Card Type</label>
        <div class="controls">
          <a href="#" class="edit_year t_year" onclick="$('#profile_card_type').toggleClass('hidedrop'); return false;">Visa</a>
          <div class="profile_year t_card_drp hidedrop" id="profile_card_type">
            <ul>
              <li><a href="#">Visa</a></li>
              <li><a href="#">Visa</a></li>
              <li><a href="#">Visa</a></li>
              <li><a href="#">Visa</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputlname">Card Number</label>
        <div class="controls">
          <input type="text" class="et_input">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputlname">Expiration Date</label>
        <div class="controls">
          <a href="#" class="edit_month t_month" onclick="$('#profile_month').toggleClass('hidedrop'); return false;">Month</a>
          <div class="profile_month t_month_drp hidedrop" id="profile_month">
            <ul>
              <li><a href="#">Jan</a></li>
              <li><a href="#">Feb</a></li>
              <li><a href="#">Mar</a></li>
              <li><a href="#">Apr</a></li>
              <li><a href="#">May</a></li>
              <li><a href="#">Jun</a></li>
              <li><a href="#">Jul</a></li>
              <li><a href="#">Aug</a></li>
              <li><a href="#">Sep</a></li>
              <li><a href="#">Oct</a></li>
              <li><a href="#">Nov</a></li>
              <li><a href="#">Dec</a></li>
            </ul>
          </div>
          <a href="#" class="edit_year t_year" onclick="$('#profile_year').toggleClass('hidedrop'); return false;">Year</a>
          <div class="profile_year t_year_drp hidedrop" id="profile_year">
            <ul>
              <li><a href="#">2000</a></li>
              <li><a href="#">2001</a></li>
              <li><a href="#">2002</a></li>
              <li><a href="#">2003</a></li>
              <li><a href="#">2004</a></li>
              <li><a href="#">2005</a></li>
              <li><a href="#">2006</a></li>
              <li><a href="#">2007</a></li>
              <li><a href="#">2008</a></li>
              <li><a href="#">2009</a></li>
              <li><a href="#">2010</a></li>
              <li><a href="#">2011</a></li>
              <li><a href="#">2012</a></li>
              <li><a href="#">2013</a></li>
            </ul>
          </div>
          <label class="control-label" for="inputfname">Security Code</label>
          <input type="text" class="et_input security_code">
        </div>
      </div>

      <div class="edit_login_text billing_detail_text">Billing Details</div>
      <hr class="password_control_group" />
      <div class="control-group">
        <label class="control-label" for="inputfname">First Name<sup class="star_red">*</sup></label>
        <div class="controls">
          <input type="text" class="et_input">
          <span class="text_under_input">TradeYa is a tight nit community, we call everybody by thier first names here.</span>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputlname">Last Name</label>
        <div class="controls">
          <input type="text" class="et_input">
          <span class="text_under_input">This will only be shared once you have confirmed a TradeYa.</span>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputfname">Address</label>
        <div class="controls">
          <input type="text" class="et_input">
          <input type="text" class="et_input add2">
          <a href="#" class="bill_state t_bill" onclick="$('#bill_states').toggleClass('hidedrop'); return false;"><%#= current_user.state.present? ? current_user.state : 'State' %></a>
          <div class="bill_states t_bill_drp hidedrop" id="bill_states">
            <ul>
              <li><a href="#">AL</a></li>
              <li><a href="#">AL</a></li>
              <li><a href="#">AL</a></li>
              <li><a href="#">AL</a></li>
              <li><a href="#">AL</a></li>
              <li><a href="#">AL</a></li>
              <li><a href="#">AL</a></li>
              <li><a href="#">AL</a></li>
              <li><a href="#">AL</a></li>
            </ul>
          </div>
          <input type="text" class="et_input zip" placeholder="Zipcode">
        </div>
      </div>
      <hr class="password_control_group" />
      <div class="control-group">
        <div class="controls save_cancel_btn next_step3">
          <input type="submit" class="edit_save" onclick="return false;" value="Next Step">
        </div>
      </div>
    </div>
  </form> -->

  <div class="complete_section form_step3" id="cardsinformation">
    <%= render 'transactions/partials/update_card' %>

  <!-- <div class="complete_section form_step3">
   
      <div class="control-group step1_control_group">
        <label class="control-label" for="inputfname">Credit Card</label>
        <div class="controls edit_payment_info" id="cardsinformation">
          <label class="radio credit_card">
            <input type="radio" name="cardtype" /><label><img src="http://d3md9h2ro575fr.cloudfront.net/images/visaicon.png" style="margin-top: -7px;"></span>
            <span class="same_shipping_text">
              <%if @my_transaction.user.charge_cards.present?%>
                Ending in <%= @my_transaction.user.charge_cards.last.last_4 %>
              <%end%>
            </span>
          </label>
          </label>
          <span class="billing_text">Billing address</span>&nbsp;&nbsp;<span class="same_shipping_text_right">Same as shipping</span>
          <hr class="password_control_group" />
        </div>
        <div class="control-group">
        <div class="controls save_cancel_btn next_step3">
          <input type="submit" class="edit_save" onclick="return false;" value="Next Step">
        </div>
      </div>
      </div>

    </div> -->
  
  <script>
  $('#add_card').click(function(){
   /* var amount = $('#amount').val(); */

   var token = function(res){
     var $input = $('<input type=hidden name=stripeToken />').val(res.id);
      $('#stripe-form-tag').append($input);
      $('#stripe-form-tag').append('<input type=hidden name=transid value=<%= @my_transaction.id %>>').submit();
   };

   StripeCheckout.open({
         key:         '<%= ENV['STRIPE_PUBLIC_KEY'] %>',
         address:     true,
         currency:    'usd',
         name:        'Add Your Credit Card',
         description: 'you are safe with us!',
         panelLabel:  'Add Card',
         token:       token
       });
   return false;
 });
  </script>
 
  
  <!-- Step3 Form End -->

  <!-- Completed Details -->
  <div class="complete_section form3_complete">
    <form class="form-horizontal">
      <div class="control-group step1_control_group">
        <label class="control-label" for="inputfname">Credit Card</label>
        <div class="controls edit_payment_info">
          <label class="radio credit_card">
            <input type="radio" name="cardtype" /><label><img src="http://d3md9h2ro575fr.cloudfront.net/images/visaicon.png" style="margin-top: -7px;"></span><span class="same_shipping_text">Ending in 9807</span></label>
          </label>
          <span class="billing_text">Billing address</span>&nbsp;&nbsp;<span class="same_shipping_text_right">Same as shipping</span>
          <hr class="password_control_group" />
        </div>
      </div>
    </form>
  </div>
  <!-- Completed Details -->
</div>

app/views/transactions/partials/_trade_header.html.erb
<div class="trade_background">
  <div class="traded_image_left"><%=render 'trades/trade_page_item_card', :item => @left_item%></div>
  <div class="traded_image_center"><img src="http://d3md9h2ro575fr.cloudfront.net/images/traded_item_icon.png"></div>
  <div class="traded_image_right"><%=render 'trades/trade_page_item_card', :item => @right_item%></div>
  <div class="traded_agreed_terms">
  	<div class="agreed_terms_heading"><img src="http://d3md9h2ro575fr.cloudfront.net/images/agreed_terms.png">Agreed Terms</div>
		
			<%= render 'trade_communications/agreed_terms_area' %>
		
  </div>
</div>

<script>
$(function(){
	$('.item_wants_image a').removeAttr('href');
	$('.card_heading_middle_left a').removeAttr('href');
	$('.item_title_card a').removeAttr('href');
	$('.item_card_name a').removeAttr('href');
	$('.traded_agreed_terms ol li img').remove();
})

</script>

app/views/transactions/partials/_trade_review.html.erb
<div class="transaction_detail_div trade_review_div" id="trade_review">
  <div class="transaction_heading trade_review_heading">
    <div class="heading_tick"><img src="http://d3md9h2ro575fr.cloudfront.net/images/tick_orange.png"></div>
    4. Trade Review
    <div class="tr_edit_btn"><a href="#" onclick="return false;">Edit</a></div>
  </div>

  <!-- Step4 Form Start -->
  <div class="form_step4">
    <%= form_tag transactions_make_trade_path do%>
    <div class="make_trade_section">
      <div class="shipping_total">
        <span>Shipping Total</span>
        <span class="trade_cost"><%= number_to_currency((@my_transaction.ship_charge + @oth_transaction.ship_charge) / 2) %></span><br><br>
        <span>Trade Points</span>
        <span class="trade_cost"><%= number_to_currency(@my_transaction.user.points / 2) %></span><span class="trade_points"><%= @my_transaction.user.points%> Points = </span>
        <hr class="cost_total_hr">
        <span class="cost_total"><%= number_to_currency(((@my_transaction.ship_charge + @oth_transaction.ship_charge) / 2) - (@my_transaction.user.points / 2)) %> </span>
        <input type="hidden" name="cost_total" value="<%= ((@my_transaction.ship_charge + @oth_transaction.ship_charge) / 2) * 100 %>">
        <input type="hidden" name="trans_id" value="<%= @my_transaction.id %>">
        <input type="hidden" name="card_id" value="<%= @card_id %>">
      </div>

      <div class="make_trade_text">
        By Clicking the “Make Trade” button, you confirm that you have read, understood, and accept our <a href="#">Terms and Conditions</a> and <a href="#">Privacy Policy</a><br><br>

        Your trade cannot be modified once it is placed.
      </div>
    </div>
    <div class="clear"></div>
    <div class="control-group">
      <div class="controls make_trade_btn next_step4">
        <%= submit_tag nil, :class=>"edit_save",:value=>"Make Trade" %>
      </div>
    </div>
  <% end %>
  </div>
  <!-- Step4 Form End -->

</div>

app/views/transactions/partials/_update_card.html.erb
 <form action="/transactions/trade_review" method="post" data-remote = "true">
      <div class="control-group step1_control_group">
        
        <label class="control-label" for="inputfname">Credit Card</label>
        <% if @my_transaction.user.charge_cards.present? %>
                <% @my_transaction.user.charge_cards.each do |card| %>
        <div class="controls edit_payment_info" id="cardsinformation">
          <label class="radio credit_card">
            <input type="radio" class="card_select" name="cardtype" value="<%= card.id %>" /><label><img src="http://d3md9h2ro575fr.cloudfront.net/images/visaicon.png" style="margin-top: -7px;"></span><span class="same_shipping_text">Ending in <%= card.last_4 %></span>&nbsp;&nbsp;<%= link_to "X", charge_card_path(card.id), method: :delete, class: "remove_card shipping_cross", data: {confirm: "Are you sure you want to delete the card?", remote: true}%></label>
          </label>
          <span class="billing_text"></span>&nbsp;&nbsp;<span class="same_shipping_text_right"></span>
          <hr class="password_control_group" />
        </div>
        <% end %>
      <% end %>
        <input type = "hidden" name = "id" value = "<%= @my_transaction.id%>">
        <div class="control-group">
        <div class="controls save_cancel_btn next_step3" id="cards_div_step">
          <input type="submit" class="edit_save" value="Next Step" id="card_step">
        </div>
      </div>
      
      </div>
    </form>
     <!-- <div class="control-group"> -->
     <!-- </div> -->

app/views/transactions/partials/_updatedaddress.html.erb
<div class="detail_form_left">
      <div class="detail_name"><%= @my_transaction.address.name %>
      </div>
      <div class="detail_address1"> <%= @my_transaction.address.address_line_1 %></div>
      <% if @my_transaction.address.address_line_2.present? %>
        <div class="detail_address1"><%= @my_transaction.address.address_line_2 %></div>
      <% end %>
        <div class="detail_address2">
          <%= @my_transaction.address.city+", "+@my_transaction.address.state+" "+@my_transaction.address.zipcode %>
        </div>
      <div class="clear"></div>
    </div>
    <div class="detail_form_right">
      <div class="detail_phone"><%= @my_transaction.address.phone %></div>
      <div class="detail_website"><%= current_user.email %></div>
    </div>
    <div class="clear"></div>

app/views/transactions/partials/_updateshippingdetails.html.erb
<div class="ship_detail_left">
      <div class="size0_detail"><img src="http://d3md9h2ro575fr.cloudfront.net/images/size1.png"></div>
      <div class="shipping_detail_name"><strong>Your item</strong></div>
      <div class="detail_item_text"><%= @transaction.weight%>lb.</div>
      <div class="detail_item_text"><%= @transaction.length %><sup>in</sup> x <%= @transaction.width %><sup>in</sup> x <%= @transaction.height %><sup>in</sup></div>
      <div class="detail_item_text"><%= @transaction.ship_notes %></div>
      <hr class="other_item_hr" style="padding-top: 15px;">
      <div class="other_item_total"><%= number_to_currency(@transaction.ship_charge) %></div>
      <div class="clear"></div>
    </div>
    <div class="ship_detail_right">
      <div class="size0_detail"><img src="http://d3md9h2ro575fr.cloudfront.net/images/size1.png"></div>
      <div class="shipping_detail_name"><strong>Other Item</strong></div>
      <div class="detail_item_text"><%= @oth_transaction.weight%>lb.</div>
      <div class="detail_item_text"><%= @oth_transaction.length %><sup>in</sup> x <%= @oth_transaction.width %><sup>in</sup> x <%= @oth_transaction.height %><sup>in</sup></div>
      <div class="detail_item_text"><%= @oth_transaction.ship_notes %></div>
      <hr class="other_item_hr">
      <div class="other_item_total"><%= number_to_currency(@oth_transaction.ship_charge) %></div>
    </div>
    <div class="ship_detail_rightmost">
      <div class="shipping_detail_name"><strong>Shipping Total</strong></div>
      <div class="detail_item_text"><%= number_to_currency(@transaction.ship_charge) %></div>
      <div class="detail_item_text"><%= number_to_currency(@oth_transaction.ship_charge) %></div>
      <hr class="shipping_hr1">
      <div class="detail_item_average"><%= number_to_currency(@transaction.ship_charge + @oth_transaction.ship_charge) %> / 2</div>
      <hr class="shipping_hr">
      <div class="detail_item_ship_total"><%= number_to_currency((@transaction.ship_charge + @oth_transaction.ship_charge) / 2) %></div>
    </div>
    <div class="clear"></div>