config/routes.rb
Tradeya::Application.routes.draw do


  resources :trade_communications


  resources :passive_trades do
    member do
      get :my_haves_tab
      get :communication_tab
      get :trader_haves_tab
    end
    resources :transactions
  end

  mount Resque::Server, :at => "/resque"

  # root :to => "home#index"
  root :to => "home#invite"
  # match 'invite' => 'home#invite'
  match 'friends_invite' => 'users#friends_invite'
  match 'home' => 'home#index'
  match 'trade_page' => 'items#trade_page'

  match 'welcome' => 'home#welcome'
  match 'holiday' => 'home#holiday'
  match 'getstarted' => 'home#getstarted'

  resources :accepted_offers, :only => [:create]
  resources :comments,:only => [:create,:destroy]
  resources :authentications
  resources :reviews

  # post 'charges/create'
  #post "charge_cards/create"
  resources :charge_cards, :only => [:index,:create,:destroy]
# mailboxer
  resources :conversations, :only => [:show] do
    member do
      post 'reply'
      get 'download'
      get 'displaytrash'
      get 'displayinbox'
      get 'trash'
      get 'markasunread'
      get 'markasread'
      get 'delete'
      get 'untrash'
      get 'newmsg'
    end
  end
  # match 'conversations/trash' => 'conversations#trash', via: [:post]

  resources :verify_phone_number do
    member { post 'twilio_hack' }
    member { post 'show' }
  end

  resources :trades do
    member do
      post :reject
      #   post :rate
      get :my_haves_tab
      get :communication_tab
      get :trader_haves_tab
      get :confirm
      post :complete
      get :accept_terms
      post :update
    end
    resources :transactions 
  end
  match "transactions/get_shipping" => "transactions#get_shipping"
   match "transactions/update_address" => "transactions#update_address"
   match "transactions/trade_review" => "transactions#trade_review"
   match "transactions/make_trade" => "transactions#make_trade"
  # Namespace for mobile api
  namespace :api, defaults:{format: 'json'} do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'
      end

      # items api calls
      get 'items' => 'items#index', :as => 'items'
      post 'items' => 'items#create'
      get 'items/:id' => 'items#show'
      post 'items/:id/likes' => 'items#likes'
      post 'items/:id/wants' => 'items#wants'
      post 'items/:id/haves' => 'items#haves'
      post 'items/:id/comment' => 'items#comment'

      get 'categories' => 'home#categories'

      # user profile api
      get 'users/:id' => 'users#show'
      get 'users/:id/likes' => 'users#likes'
      get 'users/:id/wants' => 'users#wants'
      get 'users/:id/haves' => 'users#haves'
      get 'users/:id/following' => 'users#followed_users'
      get 'users/:id/followers' => 'users#followers'
      post 'users/:id/follow' => 'users#follow'
      get 'users/:id/past_trades' => 'users#past_trades'
      post 'users/search' => 'users#search'
    end
  end

  ActiveAdmin.routes(self)
  devise_for :users,
  :controllers => {
    :registrations => 'registrations',
    :passwords => 'passwords',
    :sessions => 'sessions',
    :confirmations => 'confirmation'}
    # :invitations => 'invitations'}

  devise_scope :user do
    match 'failure' => 'sessions#failure'
    match 'update_zip' => 'registrations#update_zip', :as => :update_zip
    match 'update_account_settings' => 'registrations#update_account_settings', :as => :update_account_settings
    match 'change_user_password' => 'registrations#change_user_password', :as => :change_user_password
    match 'deactivate_account' => 'registrations#deactivate_account', :as => :deactivate_account
    match 'create_guest' => 'registrations#create_guest', :as => :create_guest, :via => :post
    match 'update_guest' => 'registrations#update_guest', :as => :update_guest, :via => :post
    match 'guest_deactivate_account' => 'registrations#guest_deactivate_account', :as => :guest_deactivate_account
  end

  # resources :items, :only => [:create, :show, :new]
  resources :items do
    member do
      post 'like'
      post 'haves'
      post 'wants'
      get 'trade_offers'
      get 'my_offers'
      get 'accepted_offers'
      get 'rejected_offers'
      get 'wants_detail'
      post 'remove_have'
      post 'remove_offer'
      post 'want_cancel'
      post 'main_photo'
      post 'request_info'
      post 'edit_photo'
    end
  end

  resources :users, :only => [:show, :edit, :update] do
    member do
      post 'follow'
      get 'dashboard'
      get 'wants'
      get 'haves'
      get 'likes'
      get 'reviews'
      get 'following'
      get 'followers'
      get 'facebook_friends'
      get 'twitter_friends'
      get 'following_tab_search'
      get 'past_trades'
      get 'myoffers'
      get 'activity_feed'
      get 'inbox'
      post 'inbox'
      get 'sort_review'
      get 'settings'
      get 'invite'
      get 'pvt_msg_tab'
      get 'messaging'
      # get 'notifications'
      get 'inbox/messaging'
      get 'inbox/notifications'
      # post 'reinvite'
      post 'resend_invite'
      post 'resend_invite_to_all'
      post 'update_settings'
      post 'update_wants_message_reminder'
      post 'user_main_photo'
      post 'delete_activity'
      post 'delete_alert'
      post 'edit_photo'
      get 'active_trades'
      get 'my_wants'
      get 'wants_on_my_haves'

    end
    resources 'addresses'
    
    collection do
      get 'check_email'
    end
  end

  get 'users' => 'users#index'
  get 'users/pvt_msg_tab' => 'users#pvt_msg_tab'
  resources :browse, :controller => "items"
  match 'edit_profile' => 'users#edit_profile'
  match 'settings' => 'users#settings'





  # resources :home, :only => [:index]

  # controller :home do
  #   match :contest, :to => 'home#contest', :as => :contest, :via => :get
  #   match :contest_send_mail, :to=> 'home#contest_send_mail', :as => :contest_send_mail, :via => :post
  #   match :contest_share, :to=> 'home#contest_share', :as => :contest_share, :via => :post
  # end


  mount Split::Dashboard, :at => 'ab-tests'

  match 'reinvite' => 'users#reinvite', :via => :post
  # match 'reject_offer' => 'trades#reject_offer'
  match 'delete_user_photo' => 'common#delete_user_photo', :via => :post
  match 'delete_item_photo' => 'common#delete_item_photo', :via => :post
  match 'reply' => 'comments#reply', via: :post
  # match 'request_info' => 'common#request_info', :as => 'request_info'
  match 'thanks' => 'common#thanks'
  match 'change_location' => 'common#change_location'
  match 'auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'common#twitter_failure'
  match 'image_preview' => 'common#image_preview'
  match 'video_preview' => 'common#video_preview'
  match "password_reset" => "common#password_reset"
  match 'is_signed_in' => 'common#is_signed_in'
  match 'is_pub' => 'common#is_pub'
  match 'sign_in_success' => 'common#sign_in_success'
  match 'facebook_sign_in_success' => 'common#facebook_sign_in_success'
  match 'modals' => 'common#modals'
  match 'privacy_policy' => 'common#privacy_policy'
  match 'tandc' => 'common#tandc'
  match 'howthisworks' => 'common#howthisworks'
  match "password_changed" => "common#password_changed"
  match "after_sign_up" => "common#after_sign_up"
  match "after_sign_up_guest" => "common#after_sign_up_guest"
  match "after_change_password" => "common#after_change_password"
  match 'contact' => 'common#contact'
  match 'twitter_share_login' => 'common#twitter_share_login'
  match 'twitter_share' => 'common#twitter_share'
  match 'linkedin_login' => 'common#linkedin_login'
  match 'linkedin_share' => 'common#linkedin_share'
  match 'publink' => 'common#publink'
  match 'tradeya_expired' => 'items#tradeya_expired'
  match 'dead_link' => 'common#dead_link'
  match 'update_profile' => 'common#update_profile', :as => :update_profile
  match 'edit_user_image' => 'common#edit_user_image'
  match 'add_verification_success' => 'common#add_verification_success'
  match 'search_my_offer' => 'common#search_my_offer'
  match 'search_my_item_wants' => 'common#search_my_item_wants'
  match 'offer_data' => 'common#offer_data'
  match 'item_want_data' => 'common#item_want_data'
  match 'rotate_video' => 'common#rotate_video'
  match 'failure_network' => 'common#failure_network'
  # match 'at' => 'common#update_auth_token'

  match 'clear_all_cache' => 'common#clear_all_cache'
  match 'clear_item_cache' => 'items#clear_cache'
  match 'clear_category_cache' => 'common#clear_cache'
  match 'clear_home_cache' => 'home#clear_cache'
  match 'test_ad_tags' => 'home#test_ad_tags'
  match 'after_update_guest' => 'common#after_update_guest'

  match 'thumb_up_down/:v/:t' => 'thumb_up_downs#thumb_up_down'

  match "update_accept_offer_modal" => "accepted_offers#update_accept_offer_modal"
  match "accept_multiple_offers" => "accepted_offers#accept_multiple_offers", :via => :post

  match "items_distance" => "items#items_distance"
  match "search_by_zip" => "items#search_by_zip"
  match "complete_trade" => "items#complete_trade", :via => :post
  match 'postpone_trade' => 'items#postpone_trade', :via => :post
  match 'crop_image' => 'items#crop_image', :via => :post
  match 'update_user_categories' => 'profile#update_user_categories', :via => :post
  match 'thumbs_down_feedback' => 'thumb_up_downs#thumbs_down_add_reason', :via => :post

  match 'dashboard' => 'home#dashboard'
  match 'manage_tradeyas' => 'home#manage_tradeyas'
  match 'manage_offers' => 'home#manage_offers'
  match 'edit_settings' => 'home#edit_settings'
  match 'edit_verifications' => 'home#edit_verifications'
  match 'mark_alert_read_and_redirect' => 'home#mark_alert_read_and_redirect'
  match 'refresh_alert_count_and_show_new' => 'home#refresh_alert_count_and_show_new'

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trade_id %><br />
    <%= f.number_field :trade_id %>
  </div>
  <div class="field">
    <%= f.label :charge_id %><br />
    <%= f.number_field :charge_id %>
  </div>
  <div class="field">
    <%= f.label :trans_charge %><br />
    <%= f.text_field :trans_charge %>
  </div>
  <div class="field">
    <%= f.label :ship_charge %><br />
    <%= f.text_field :ship_charge %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Trade</th>
    <th>Charge</th>
    <th>Trans charge</th>
    <th>Ship charge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.trade_id %></td>
    <td><%= transaction.charge_id %></td>
    <td><%= transaction.trans_charge %></td>
    <td><%= transaction.ship_charge %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<script src="https://checkout.stripe.com/v2/checkout.js"></script>

<div class="container transaction_width">
  <div class="span10 item_middle_section">
    <div class="center_content">
      <div class="transaction_wrapper">

        <%= render 'transactions/partials/trade_header' %>

        <!-- Your Detail Section Start -->
        <%= render 'transactions/partials/user_details' %>
        <!-- Your Detail Section End -->

        <!-- Shipping Detail Section Start -->
        <%= render 'transactions/partials/shipping_details' %>
        <!-- Shipping Detail Section End -->

        <!-- Payment Section Start -->
        <%= render 'transactions/partials/payment_details' %>
        <!-- Payment Section End -->

        <!-- Trade Review Section Start -->
        <%= render 'transactions/partials/trade_review' %>
        <!-- Trade Review Section End -->

      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
$(document).ready(function(){
  $('.payment_heading .tr_edit_btn').show();
  $('.form_step1').hide();
  $('.form_step2').show();
  $('.form1_complete').show();
  $('.your_detail_heading').css('background-color','#EEEBE0');
   $('.your_detail_heading').css('color','#3d362d');
  $('.your_detail_heading .heading_tick').show();
  $('.your_detail_heading .tr_edit_btn').show();

});
 $('.form_step2').hide();
 $('.form_step3').hide();
 $('.form_step4').hide();
 $('.heading_tick').hide();
 $('.tr_edit_btn').hide();
 $('.transaction_heading').css('padding-left','20px');
 // $('.shipping_detail_heading').css('background-color','#EEEBE0');
 // $('.shipping_detail_heading').css('color','#3d362d');
 $('.payment_heading').css('background-color','#EEEBE0');
 $('.payment_heading').css('color','#3d362d');
 $('.trade_review_heading').css('background-color','#EEEBE0');
 $('.trade_review_heading').css('color','#3d362d');
 $('.form1_complete').hide();
 $('.form2_complete').hide();
 $('.form3_complete').hide();

 $('.next_step1').click(function(){
   $('.form_step1').slideUp('slow');
   $('.form_step2').slideDown('slow');
   $('.your_detail_heading').css('background-color','#EEEBE0');
   $('.your_detail_heading').css('color','#3d362d');
   $('.shipping_detail_heading').css('background-color','#3d362d');
   $('.shipping_detail_heading').css('color','#fff');
   $('.transaction_heading.your_detail_heading').css('padding-left','10px');
   $('.your_detail_heading .heading_tick').show();
   $('.your_detail_heading .tr_edit_btn').show();
   $('.form1_complete').show();
 });
 $('.next_step2').click(function(){
   $('.form_step2').slideUp('slow');
   $('.form_step3').slideDown('slow');
   $('.shipping_detail_heading').css('background-color','#EEEBE0');
   $('.shipping_detail_heading').css('color','#3d362d');
   $('.payment_heading').css('background-color','#3d362d');
   $('.payment_heading').css('color','#fff');
   $('.transaction_heading.shipping_detail_heading').css('padding-left','10px');
   $('.shipping_detail_heading .heading_tick').show();
   $('.shipping_detail_heading .tr_edit_btn').show();
   $('.form2_complete').show();
   $('.form_step3').css('background-color','#EEEBE0');
 });
 $('.next_step3').click(function(){
   // $('.form_step3').slideUp('slow');
   $('.form_step4').slideDown('slow');
   $('.payment_heading').css('background-color','#EEEBE0');
   $('.payment_heading').css('color','#3d362d');
   $('.trade_review_heading').css('background-color','#3d362d');
   $('.trade_review_heading').css('color','#fff');
   $('.transaction_heading.payment_heading').css('padding-left','10px');
   $('.payment_heading .heading_tick').show();
   $('.payment_heading .tr_edit_btn').show();
   $('.form_step3').css('background-color','#fff');
   // $('.form3_complete').show();
   $('.save_cancel_btn.next_step3').hide();
 });
 $('.next_step4').click(function(){
   $('.form_step4').slideUp('slow');
   $('.trade_review_heading').css('background-color','#EEEBE0');
   $('.trade_review_heading').css('color','#3d362d');
   $('.transaction_heading.trade_review_heading').css('padding-left','10px');
   $('.trade_review_heading .heading_tick').show();
   $('.trade_review_heading .tr_edit_btn').show();
 });

 $('.your_detail_heading .tr_edit_btn').click(function(){
   $('.form1_complete').hide();
   $('.form_step1').slideDown('slow');
   $('.your_detail_heading').css('background-color','#3d362d');
   $('.your_detail_heading').css('color','#fff');
   $('.transaction_heading.your_detail_heading').css('padding-left','20px');
   $('.your_detail_heading .heading_tick').hide();
   $('.your_detail_heading .tr_edit_btn').hide();
 });

 $('.shipping_detail_heading .tr_edit_btn').click(function(){
   $('.form2_complete').hide();
   $('.form_step2').slideDown('slow');
   $('.shipping_detail_heading').css('background-color','#3d362d');
   $('.shipping_detail_heading').css('color','#fff');
   $('.transaction_heading.shipping_detail_heading').css('padding-left','20px');
   $('.shipping_detail_heading .heading_tick').hide();
   $('.shipping_detail_heading .tr_edit_btn').hide();
 });

 /* TODO: enter amount and char desc */
 


 /*
 $('.payment_heading .tr_edit_btn').click(function(){
 $('.form3_complete').hide();
 $('.form_step3').slideDown('slow');
 $('.payment_heading').css('background-color','#3d362d');
 $('.payment_heading').css('color','#fff');
 $('.transaction_heading.payment_heading').css('padding-left','20px');
 $('.payment_heading .heading_tick').hide();
 $('.payment_heading .tr_edit_btn').hide();
 });

*/
$('#getShippingSubmit').click(function(){
   get_shipping();
   return false;
});

 $('.trade_review_heading .tr_edit_btn').click(function(){
   $('.form3_complete').hide();
   $('.form_step3').slideDown('slow');
   $('.trade_review_heading').css('background-color','#3d362d');
   $('.trade_review_heading').css('color','#fff');
   $('.transaction_heading.trade_review_heading').css('padding-left','20px');
   $('.trade_review_heading .heading_tick').hide();
   $('.trade_review_heading .tr_edit_btn').hide();
 });
</script>
<script>
  $('#edit_cards').click(function(){
      $('input.card_select').prop('disabled',false);
      $('#cards_div_step').show(); 
      $('#add_card').show();
  });

</script>

app/views/transactions/update.js.erb
$("#updateshippingdetails").html("<%= raw escape_javascript(render 'transactions/partials/updateshippingdetails') %>")

app/views/transactions/update_address.js.erb
$("#updatedaddress").html("<%= raw escape_javascript(render 'transactions/partials/updatedaddress') %>")